### ISSUE TITLE
“Expression has changed after it was checked”

### ISSUE THREAD

**Issue by christiandreher** [urish/angular2-moment#84] opened 2016-10-03 17:06 UTC
I can't reopen #48, so I decided to open a new issue.
Well: #48 is still relevant, even with Angular 2.0.1, the error does still occur.
It's easy reproducable when you have lots of pipes which change fast. For me, it happens nearly all the time when I add a few datasets which have a TimeAgoPipe associated with them

**Comment by christiandreher** [comment] 2016-10-03 17:11
Also relevant: #48 and #55

**Comment by brettkc** [comment] 2016-10-10 19:11
Seeing this issue also with an observable subscription that changes every 15 seconds~

**Comment by nithril** [comment] 2016-10-16 21:06
Same issue, it appears when the timeAgo changes from second to minutes ago and when the dataset is completly refreshed with an observable subscription.

**Comment by nithril** [comment] 2016-10-27 18:36
Here is a plunkr with the issue
http://plnkr.co/edit/MITgrJ3drTDzyzJ0CjVo?p=preview

**Comment by urish** [comment] 2016-10-27 23:33
@nithril thank you for creating an example that reproduces the issue.

Seems like it has to do with the way Angular change detection works - this is the line where the exception is thrown:

https://github.com/angular/angular/blob/32feb8a5328221eedaece8f5212b0d9b65210a42/modules/%40angular/core/src/linker/view_utils.ts#L137

`throwOnChange` can only be true in development mode, and it seems that the check is initiated from this code:

https://github.com/angular/angular/blob/745e10e6d2ea9097b7ec650ae54cea91e3d193f2/modules/%40angular/core/src/application_ref.ts#L476

i.e. when you are in development mode, Angular tries to validate that bindings do not change by running the change detection process twice, and checking if the first iteration and the second one result in the same value for all bindings. Since each iteration is run at a different time, there is a small chance that `amTimeAgo` will return a different value. Of course this is not harmful, this is exactly the intended behavior of the plugin, however, Angular is not happy with that when you are in development mode.

We can probably implement some workaround to make angular happy in development mode, but I am not sure that we want to do this - it will add a bunch of logic just to make angular think that we behave differently from the way we actually do.

**Comment by nithril** [comment] 2016-10-28 07:41
A workaround could be to define a mutable string object. The pipe transform will create one instance and only update the content.

```
var MutableString = function(value) {
  this.text = value;
};
 MutableString.prototype = {
  toString: function() {
    return this.text;
  }
};
```

**Comment by christiandreher** [comment] 2016-10-28 10:11
However, this issue needs to be fixed somehow eventually, because for me, there is a big chance for this error to occur, which makes development really hard for me (I need a full reload everytime this error is thrown...)

**Comment by urish** [comment] 2016-10-28 10:36
@nithril very creative workaround! Any chance you can try it and report back if it actually works?

By looking at the current implementation of [`devModeEqual`](https://github.com/angular/angular/blob/32feb8a5328221eedaece8f5212b0d9b65210a42/modules/%40angular/core/src/change_detection/change_detection_util.ts), it seems like if both values are not primitives nor iterables, it will always return true.

**Comment by nithril** [comment] 2016-10-28 12:23
I will try today or tomorrow

**Comment by urish** [comment] 2016-10-28 12:25
Thank you!

**Comment by nithril** [comment] 2016-10-29 08:12
It is not as simple, angular uses the toString to make the comparison.

I have moved the time ago computation from the `transform` method to the timer callback. The mutation is inside a timeout callback, followed by a `markForCheck`. Angular supports [this pattern](https://angular.io/docs/js/latest/api/core/index/ChangeDetectorRef-class.html#!#markForCheck-anchor).

what do you think about this [plunkr](http://plnkr.co/edit/EwJwI11uelrsMR4z17x8)?

**Comment by urish** [comment] 2016-10-29 09:58
Thanks! It seems to do the trick. There is one edge case though, which I don't believe is very common:

since moment instances are mutable, they can be mutated and we won't detect this with the current implementation. 

You can see [this plunkr](http://plnkr.co/edit/nXfkCAEgjQW6ARSAo5BE?p=preview
) for an example: click on "Make them old" (which makes the timer fire every hour) and then click on "Reset", and you will see that even though the Moment objects were updated, the view still says "a year ago".

I believe this can be solved by comparing the actual time value instead of the moment instances.

**Comment by nithril** [comment] 2016-10-29 22:13
well done, I haven't thought to this use case, I expected immutability. I have updated the [plunkr](http://plnkr.co/edit/eLlq2mJEojt7SJjg7nbN)

**Comment by urish** [comment] 2016-11-03 10:40
Thanks! Can you please turn this into a PR? If you need assistance with the unit tests let me know, I would love to have this merged in before we cut the 1.0.0 release

**Comment by nithril** [comment] 2016-11-03 23:15
I will do the PR this week end.

**Comment by urish** [comment] 2016-11-03 23:19
Awesome, thanks!

**Comment by urish** [comment] 2016-11-11 18:58
Fixed in 1.0.0-rc.1

**Closed by urish** 2016-11-11 18:58 UTC

**Comment by nithril** [comment] 2016-11-12 19:28
Thanks!

**Comment by christiandreher** [comment] 2016-11-12 20:08
Thank you very much, @nithril
